#设置服务名
spring: 
   application: 
      name: config-server
   profiles: 
      active: native #使用本地文件存储配置文件,自动搜索resources目录下的文件
   cloud: 
      config: 
         server: 
            native:
               searchLocations: classpath:/config/dev/
server:
   port: 9900
#注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9910/eureka